GET http://localhost:8080

###

GET http://localhost:8080/alunos

###

GET http://localhost:8080/alunos/1bfaaa84-1cea-44a6-b5c3-66d677300e13

###

POST http://localhost:8080/alunos
content-type: application/json

{
    "nome": "pedrin"
}

###

PUT http://localhost:8080/alunos?id=43636b4c-eb3b-4dd5-b755-5c8be3d27a0c
content-type: application/json

{
    "nome": "paulin bacana"
}

###

DELETE http://localhost:8080/alunos?id=43636b4c-eb3b-4dd5-b755-5c8be3d27a0c
